AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to create an S3 bucket, EC2 instance, and enable private Git repository cloning.

Parameters:
  PrivateSSHKey:
    Type: String
    NoEcho: true
    Description: Private SSH key to clone the project from Git

Resources:
  TestS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-cloudformation-deployment

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: "arn:aws:s3:::test-cloudformation-deployment/*"

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and Node.js application port"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: "0.0.0.0/0"

  SampleNodejsDeploy:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-053b12d3152c0cc71
      InstanceType: t2.micro
      IamInstanceProfile: !Ref EC2Role
      SecurityGroups:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          apt-get update
          apt-get install -y git curl
          mkdir -p /home/ubuntu/.ssh
          echo "${PrivateSSHKey}" > /home/ubuntu/.ssh/id_rsa
          chmod 600 /home/ubuntu/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> /home/ubuntu/.ssh/known_hosts
          cd /home/ubuntu
          git clone git@github.com:kevit-dev-bhayani/Test-cloud-formation-deployment.git
          cd Test-cloud-formation-deployment
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
          npm install
          npm install -g pm2
          pm2 startup
          pm2 save
          pm2 start npm --name "Test-cloud-formation-deployment" -- start -p 3000

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket created
    Value: !Ref TestS3Bucket
